name: tang0
description: "cross tab communication boilerplate"
version: 0.0.1
homepage: https://github.com/ZackaryW/tang0

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

platforms:
  web:

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.3
  web: ^1.1.1
  flutter_secure_storage: ">=9.2.0 <10.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0